name: Add question
description: What?
title: " "
labels: ["question"]
assignees:
  - BruceGitHub
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: data
    attributes:
      label: Questions
      description: More detail question 
      placeholder: 
      value: " "
    validations:
      required: true
